# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Vulnerability Scan
on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  scan:
    name: Scan docker image with trivy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag angular-ngrx-frontend:master

      # Cannot use because of - https://github.com/homoluctus/gitrivy/issues/59
      - name: Scan image with trivy
        uses: lazy-actions/gitrivy@v3
        with:
          image: angular-ngrx-frontend:master
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          ignore_unfixed: true
          token: '${{ secrets.GITHUB_TOKEN }}'
