# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Vulnerability Scan
on:
  schedule:
    - cron: '0 12 * * *' # Run every day at 12:00 UTC
  workflow_dispatch:

jobs:
  scan:
    name: Scan docker image with trivy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.0

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag angular-ngrx-frontend:master

      - name: Scan image with trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: angular-ngrx-frontend:master
          ignore-unfixed: 'true'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
